language: java
jdk:
- openjdk8
sudo: false
install: "./installViaTravis.sh"
script:
- "./buildViaTravis.sh"
- "./gradlew codeCoverageReport"
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: V+K6B2s3kRV2y9eMJJ32y2vqVFIp8R+lXrjGq+mw3au147XEdbXpDMSh8pOo0AL4MaOWb85yVdNOCrwfvjPg5S98P6ZMt+tSACHj4gt+8odID8BkYWt6yJIgue+fCysVyLfsS9X+7bqHQA3p5KqmIueuqni3E6/c89TKTC0WS7w=
  - secure: TlGo0nG+g1+7oW18uNKpt/EL+3BruhpLy4CUMmdZJ9ciyzL+iFtw2Iy8I9UHe/TYzu78D5NEcULdI+CToQp6ELKz2jvEao+iB4MtHkNw00Or7E/bci5QXW0RuEDYsNE0Y3pzYwULZjoV0IWfL2Jq4DJPRPhxCjJtfYHEVBCj/r8=
  - secure: s6mhGCg2bn8aFpG1iScsnSHaem9+xrp2I9h4UOGtK+alafuoPnKUP8GLshp58wHYcdUs0zaG4wvw+4i2Ie2QyyUzKTEx1qRe6esxCqx1F8dyw8j51dhXC0lDS8aShHRCakJHefEs1Gi4ECmTfqc2w7A4DFa8ECjtz84cQ8UplqE=
  - secure: EpNMulXv9VNVIG1WYPdNppSMVfY0JQ25j1m3Hzb3oqfOkqyhp1pLI54TlF3ks77qgDjyCEa1kk49g4ONvzzh6vp0DH6bLis1LYSvjUXowmGAhluOr8JDlPcBf6BeeVLOXYakxk37/ErYQRAyui2VVcABEspbFM7ANhI8r7Z99eQ=
  - secure: jCP93MvQMoIDnyXi4v3tz8ZMVcT365rAMPL4JkzELXFXq91Z/CTKG5SQuh4F9JbKD+yYQPPC0gpABMieER1HqNuSeQ9DsPssD3cG2XZ2oomOdnljilYYj2GFXrFhG+7zfcdCKr8idacQFn33D/pd7O6c6vHrrz6a7KuydiPqy7g=
  - secure: F6+6GMeG1HiG0pxUSwBzk6INyzurfPw1DCremO/UBulbGIX1a4JVuPePes9FUCp7l9FIf3b5PH4tOS8XlO9HYL3noh0r26FgB9atoh6xvOERLCtABrGml/qeN7E8VYXCTP7XvaNF/31Yo06rXGw7Owig57hnnEnkmgwgJKbAnIo=
