language: java
jdk:
- openjdk8
sudo: false
git:
  depth: 100
install: "./installViaTravis.sh"
script: "./buildViaTravis.sh"
cache:
  directories:
  - "$HOME/.gradle"
env:
  global:
  - secure: bXzjPA0Ec3NBIN25knd9UYzGtxxmlhoLkO0LwI87iRSeCLzvbT+qBl/chvaXCk3DC2JnSq6GGWw2r0R6pjR4UezZx72KP+dm19cy606e7np1mHZmzziSkyjaBd84HPgOz8L4jh5G9qQBG8VhkjikIabAgsbiWG3oX6a/rOadobg=
  - secure: COIxG87u7BSBAD0s8g0E9PTq4XLompgW/PL55bnIxuVkIo3tXXqShAxMzsJ0C++q5AbofNUICqTbGqN0ozk9GpMC78d5pgWS1O4hpdWsouK8Fxcju+KkKC5MUDC478G/zW0uSa0uZsZGaDy3Gx17jpvq2CdVCgHmaHmGGOxfDbA=
  - secure: LMyJ2v4kN+07Gz5pPHkYLOvbQOAI05bHFGUVfaAbofyiR1DqKpKqB4hYaKSgb0kB/3YI6u9dLQ5AWzAqfx3HY0+p2iTmgseIxbHGrFfOH7bt2xusYNUtYPn1JXOAz1Nzxq/a+4rCgqD9lFI19XetrI5SNrRIRErDIZnWdXyhW/M=
  - secure: dxJVfXpC/yORQWg2oaw+Q2UjeoAHiqf5hyLVSdGbIJYVrSu/fyFCuUNjQffikjleoyuaPeIHxaGQZoQZE3+9Cf3d7s1lXzugO3UOxmKR9UYi8tz6sLUFeLPjVhR6Etx603A8oCg659RhD2VyOCZvq1/R2gUa34tUtnVyoFyUzDA=
  - secure: tl59nbZhOzWqW/PLp91+Paugond4Lwwj/qT1Tq4EFJ9Q2nNMFW3twlWzmUOcgn7GaJZTgfoDx2HGYFg1N3rrBtZIY/Wtzz9eWrGY4ywHfoXz/8lQGtbciDjiNePByuvSLOPWeTIGncOLGNUcCPNFOO9+kC4BzUGr9CjtTc+qnWg=
  - secure: AZoBLO43P+GVjQq+vsT8mekOUNqifi+tRYukz19GLN2vv2vsgY4ejhXjeer1kwqm0l/1bXtfqo0uHyD+CFn2yINV20oKHScYNS4fwKnJ8aC60MZqAj6zddfe2VvEeDIKDiejpz4AfRJwgqpl9B0FrNtZ/1oU5n8oneTKpVFryTs=
