site_name: 'Priam'
repo_name: 'Netflix/priam'
theme: 'material'
repo_url: https://github.com/Netflix/priam
site_author: Netflix
copyright: Copyright 2018 Netflix, Inc.
extra:
  feature:
    tabs: false
markdown_extensions: 
  - codehilite    
nav:
  - "Home": "index.md"
  - "Installation": "latest/mgmt/installation.md"
  - "Management Tasks": "latest/management.md"
  - "Contributions": "latest/mgmt/contributions.md"
  - "Presentations": "latest/mgmt/presentations.md"
  - "FAQ": "latest/faq/faq.md"
